// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr9WY1SNbc92nSVsyIkramLU4xHtbvWeI',
    appId: '1:783938353590:web:ab37dbc6e2d77057da6917',
    messagingSenderId: '783938353590',
    projectId: 'todo-app-route-872ea',
    authDomain: 'todo-app-route-872ea.firebaseapp.com',
    storageBucket: 'todo-app-route-872ea.appspot.com',
    measurementId: 'G-V54387SSBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClJk-msoFgGsCEZtldQVhZSjCnefYizfE',
    appId: '1:783938353590:android:34054dc0a364d8bdda6917',
    messagingSenderId: '783938353590',
    projectId: 'todo-app-route-872ea',
    storageBucket: 'todo-app-route-872ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqSFTAwWNx2W92qdZgzbOCHcdfB3dTtXw',
    appId: '1:783938353590:ios:a6e3e075fc8bdafcda6917',
    messagingSenderId: '783938353590',
    projectId: 'todo-app-route-872ea',
    storageBucket: 'todo-app-route-872ea.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqSFTAwWNx2W92qdZgzbOCHcdfB3dTtXw',
    appId: '1:783938353590:ios:307146e5591f9c98da6917',
    messagingSenderId: '783938353590',
    projectId: 'todo-app-route-872ea',
    storageBucket: 'todo-app-route-872ea.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
